url: "https://w3id.org"
baseurl: /sml
remote_theme: redmer/minimaal
title: Semantic Modelling and Linking
description: "CEN-EN 17632 Part 1+2: Semantic Modelling and Linking"
lang: en
timezone: Europe/Amsterdam
repo: https://github.com/stichting-crow/sml

minimaal:
  nested_links: false
  disable_seo: true

staticld_ghpages:
  input_files:
    - data/sml-owl.ttl
    - data/sml-rdfs.ttl
    - data/sml-shacl.ttl
    - data/sml-skos.ttl
    - data/sml2-owl.ttl
    - data/sml2-rdfs.ttl
    - data/sml2-shacl.ttl
    - data/sml2-skos.ttl
  onto_base: "https://w3id.org/sml/def#"
  vocab_base: "https://w3id.org/sml/term#"
  linked_ns:
    - "sml"
    - "sml-term"
  graph_order:
    - data/sml-skos.ttl
    - data/sml2-skos.ttl
    - data/sml-rdfs.ttl
    - data/sml2-rdfs.ttl
    - data/sml-owl.ttl
    - data/sml2-owl.ttl
    - data/sml-shacl.ttl
    - data/sml2-shacl.ttl
